[project]
name = "meterhub"
version = "0.1.0"
description = "SDK for MeterHub"
authors = [
    {name = "svtter", email = "svtter@qq.com"},
]
dependencies = [
    "requests>=2.32.3"
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
